### ISSUE TITLE
CVE detection in CI

### ISSUE THREAD

**Issue by alltilla** [axoflow/axosyslog#190]
Based on a suggestion from @ikheifets-splunk: https://github.com/axoflow/axosyslog/issues/186#issuecomment-2208933715

**Comment by ikheifets-splunk** [comment]
I published [PR](https://github.com/axoflow/axosyslog/pull/191) for that issue and [I tested on my fork and it's working](https://github.com/ikheifets-splunk/axosyslog/actions/runs/9797432944/job/27054104815).

Only one thing I wanna highlight we on CI allowing it to fail (I mean that non blocking release), because some of the security might be unresolved or problematically solve it asap. As I remember we setup require policy on Github settings

**Comment by ikheifets-splunk** [comment]
I just wanna ask one thing. Is it will be possible to release security hot fixes that will detect CI? 
Because I know your release cycle is once per 2-3 months.

**Comment by ikheifets-splunk** [comment]
@alltilla can you take a look?

**Comment by alltilla** [comment]
I am on PTO this week, but probably @MrAnno or @bshifter can help.
