### ISSUE TITLE
systemd-journal support?

### ISSUE THREAD

**Issue by akunszt** [axoflow/axosyslog#72]
I know Alpine Linux does not use systemd so this might be won't do, but I'll ask anyway.

We are using a syslog-ng based DaemonSet to fetch both the node and Kubernetes pod logs. The host logs are fetched with systemd-journald() (required volumes are mounted to the syslog-agent pod) and the pod logs are collected with a wildcard-file() (those volumes mounted too) as no kubernetes() is available in the version we use. This is one of the reason why we would like to upgrade.

Also we are using both AMD64 and ARM64 machines.

Now we are building our own images by installing the packages offered by the distribution. Our issue is that those lags behind the latest and greatest available.

We tried the official syslog-ng image but that does not have ARM64. We tried axosyslog but that does not have journald support. Is there a way where we can have journald support on ARM64?

**Comment by bazsi** [comment]
I've just checked if libsystemd could be added easliy, but it does not seem to be the case. I've only found this:

https://github.com/Artox/alpine-systemd

Which is a 3yrs old compilation of libsystemd for alpine. It probably does not matter much, but that could easily become a security support nightmare. https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=systemd

potential solutions:

1) use a different route for local logs

I'd consider trying to collect local host logs with a different means (e.g. forward /dev/log somehow). 

systemd does have a ForwardToSyslog option, just be sure to check for truncation (IIRC there was an issue that /dev/log forwarding truncated logs at 1024 bytes).

Also, you could use syslog-ng as the owner of the /dev/log socket (instead of the journald) and have syslog-ng forward those to systemd, if having the journal as well is important.

2) build your own ubuntu based containers for arm64/amd64 from the github packages.

we are also open to contributions here, maybe an alternative axosyslog image, running ubuntu could make sens to address this case.

3) run a small host-level service that takes journal logs and forwards them to the daemonset.

**Comment by akunszt** [comment]
@bazsi Thanks for checking. I think I will go with option 2. Option 1 is hard to accomplish in our environment (we are using Flatcar Linux which ships only systemd-journald and everything else should be deployed by using containers).
Now I am working on some s3 destination improvements so we can compare syslog-ng and Vector as an S3 sink. I can build the image after that, assuming that my work schedule makes it possible. If I succeed then I will open a PR here to share the Dockerfile(s) so you can take it if it is still needed.

**Comment by bazsi** [comment]
As I mentioned systemd can forward to syslog, so option 1) can still be viable. Just ping me on discord so we can possibly discuss.

**Comment by akunszt** [comment]
@bazsi I tried to sign on Discord but it just didn't let me. I really don't know why...

When I last tried option 1 aka setting ForwardToSyslog then it wasn't worked due this:
```
If forwarding to syslog is enabled but nothing reads messages from the socket, forwarding to syslog has no effect.
```
We deploy the syslog-ng agent through Kubernetes as a DaemonSet because we use the pod network to collect the logs. So the agent starts up way after the bootstrap and we are interested in the bootstrap logs too. Our current solution (access journald from the pod) works well, we just stuck on 3.35 as that is the latest in AlmaLinux which supports both AMD64 and ARM64. The kubernetes source was introduced in a later version (maybe 3.36?). It is just an awkward situation.
Now we are concentrating on the S3 sink usability first. Vector is a great tool, it offers a lot of configuration options, but their syslog engine cannot be compared to syslog-ng. We have recurring issues both in stability and performance.

**Comment by bazsi** [comment]
I'd love to understand your use-case better and nail this issue once and for all. Just send me an email at balazs.scheidler@axoflow.com and then let's take it from there (e.g. set up a call and/or fix discord).
